### ISSUE TITLE
Having both hybridsessions and testsession causes logout every other request

### ISSUE THREAD

**Issue by IgorNadj** [silverstripe/silverstripe-hybridsessions#23]
silverstripe/hybridsessions 1.1.0 # 62bbde43f95f17ec829d00bcf6d9a80ebddd6d6c
silverstripe/testsession 0.2.x-dev # 97cf9f15c3fb42a5a5deeade1c4e9fc2c33b0dd2

It looks like the Session::start() call in testsession:

https://github.com/silverstripe/silverstripe-testsession/blob/97cf9f15c3fb42a5a5deeade1c4e9fc2c33b0dd2/code/TestSessionEnvironment.php#L60

No idea why, but this seems to drop the session? and force a re-login every other request.

**Comment by robbieaverill** [comment]
I've assigned a low impact since it's unlikely to affect users outside of development environments.

**Comment by robbieaverill** [comment]
Changed to medium to be more accurate

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
