### ISSUE TITLE
Replace mcrypt with openssl for PHP 7.2 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-hybridsessions#26]
Since mcrypt is deprecated and removed in PHP 7.2, we'll need to ensure that we either use a shiv library to replace it, or better would be to replace it with openssl use instead.

Related https://github.com/silverstripe/silverstripe-framework/issues/7280

**Comment by wilr** [comment]
Fixed in #27

**Comment by robbieaverill** [comment]
Reopened as we now need to backport this to SilverStripe 3 as well

**Comment by robbieaverill** [comment]
The changes in #27 aren't going to be easy to backport since they're very breaking changes. `HybridSessionStore_Crypto` is designed to work with mcrypt - I'll try and backport the OpenSSL equivalent from #27 and make it pluggable in the SS3 version without changing any other APIs

**Comment by robbieaverill** [comment]
Nevermind, 4b0bae8ecd095ec81915a513c4b28ff7a77ff8fc actually changed the module to use OpenSSL anyway. I'll update the documentation and make a PR for it.

**Comment by robbieaverill** [comment]
Fixed in the 1.2 branch
