### ISSUE TITLE
Module (currently) only works with MySQL, but does not guard it's tests properly

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-hybridsessions#37]
When using another adapter to speed up tests (such as `silverstripe/sqlite3`) this results in a set of false failures. The tests should be marked as skipped instead.

**Comment by dhensby** [comment]
it may be better to make the tests driver agnostic? do you have the test run failures you can share?

**Comment by NightJar** [comment]
That would require the whole module to support a db driver agnostic approach. I'm scoping that outside this issue (although a valid point) as I just don't want red herring failures popping up all over when I test :)

**Comment by dhensby** [comment]
a-ha - I see, yep, lets skip the tests then
