### ISSUE TITLE
Backport #31 to SS3

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-hybridsessions#43]
#31 (fixed in #32)  was fixed for SS4 only. 

Following an upgrade to PHP 7.1 on an SS3 site, users were unable to log in to the CMS. It could be related to this.

**Comment by robbieaverill** [comment]
I'll add it was reported that this only affects users with active DR enabled. It'd be good for someone to validate that the patch at #31 fixes the bug in an active DR environment before we backport it. Note that backporting the change won't be much work.

**Comment by NightJar** [comment]
Closed with #44
