### ISSUE TITLE
DatabaseStore is not binary safe

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-hybridsessions#49]
DatabaseStore persists session serialized data as text. However, PHP strings are binary blobs and may contain invalid bytes (e.g. "\x80" is a valid PHP string, but invalid UTF-8 string).

In case $_SESSION has some binary data in it, DatabaseStore corrupts the session data when trying to persist it in the database.

P.S. CookieStore handles binary data gracefully, the problem is only with DatabaseStore

**Comment by sminnee** [comment]
It's worth noting that using a BLOB rather than a TEXT would have also fixed this. The change made here is fine, but next time storage of arbitrary-length binary data comes up perhaps we need to introduce DBBlob to framework?

**Comment by dnsl48** [comment]
Yes, that's exactly what we discussed with the team the other day. We need to introduce DBBinary field, otherwise that's the most elegant solution we could come up with.

**Comment by dnsl48** [comment]
The issue has been fixed in the version [2.1.2](https://github.com/silverstripe/silverstripe-hybridsessions/releases/tag/2.1.2)
