### ISSUE TITLE
McryptCrypto / loses zero byte in the end of data blob

### ISSUE THREAD

**Issue by dnsl48** [silverstripe/silverstripe-hybridsessions#53]
It appears McryptCrypto is not completely binary safe.
It loses zero bytes (`"\x00"`) from the end of messages being encrypted.

Here are the tests failing:
 - https://travis-ci.org/silverstripe/silverstripe-hybridsessions/jobs/552559290
 - https://travis-ci.org/open-sausages/silverstripe-hybridsessions/jobs/552562879

The tests there are as follows:
```php
$key = random_bytes(8);
$salt = random_bytes(16);

$handler = new McryptCrypto($key, $salt);

for ($i = 0; $i < 1000; ++$i) {
    $data = random_bytes(1024 * 4);
    $this->assertEquals($data, $handler->decrypt($handler->encrypt($data)));
}
```

**Comment by robbieaverill** [comment]
Let's just deprecate McryptCrypto. People should be using OpenSSL now anyway.

**Comment by dnsl48** [comment]
I think that's already deprecated. I guess removing the component will be the fix for this issue :)

**Comment by robbieaverill** [comment]
If you want to create a `2` branch off master then make master 3.x-dev then go for gold. `McryptCrypto` is not deprecated, but the underlying PHP library is. This is probably an oversight during our upgrade than anything

**Comment by dnsl48** [comment]
soz, I don't have write access this repo. I guess I'll leave it as is for now :)

**Comment by robbieaverill** [comment]
All good, I'll deprecate the class name

**Comment by robbieaverill** [comment]
OK deprecation PR is at #54. I don't think we should invest time into fixing this bug. If you agree, let's close it.

**Comment by dnsl48** [comment]
Sure. Let's also add a note to its documentation about losing zeroes so it becomes a documented limitation?

**Comment by robbieaverill** [comment]
I think you know more about it than I do. Would you mind making a PR for that?

**Comment by dnsl48** [comment]
here we go - https://github.com/silverstripe/silverstripe-hybridsessions/pull/55
