### ISSUE TITLE
Lack of PHP 7.2+ compatibility for 1.1 branch

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-hybridsessions#56]
Identified by a server error on install: `ERROR: Uncaught Error: Call to undefined function mcrypt_get_iv_size()`

Looks like the required package `"ext-openssl": "*",` includes `ext-mcrypt` which is depreciated in PHP 7.1 and removed in PHP 7.2

**Comment by robbieaverill** [comment]
We may need to merge the branches up, it was fixed in 1.something already. Sec...

**Comment by robbieaverill** [comment]
Not a missing merge up. Are you sure that error isn't coming from a different part of your codebase, and that you're actually using 1.x of this module?

**Comment by brynwhyman** [comment]
Reporter was using version 1.1 of the module. Looks like the 1.2-rc1 branch has the patch to fix this?

**Comment by emteknetnz** [comment]
yup 1.2.0-rc1 version seems to work correct is you're using cwp 1.9.2-rc2 / php 7.3

**Comment by robbieaverill** [comment]
We released the new minor version to add PHP 7.2 support. It can't really be justified as a patch change since it switches from mcrypt to openssl as the default encryption provider. The fix is to use 1.2.x

**Comment by NightJar** [comment]
Thanks @robbieaverill - I note that 1.2.x is currently RC only, I'm thinking to just release it. Was there any particular reason you can recall as to why it was released as RC to begin with?

**Comment by robbieaverill** [comment]
It was part of CWP 1.9’s release candidate

**Comment by NightJar** [comment]
Normally we tag modules as stable though, only recipes go through release candidate phases.
Is your recommendation to wait for stable release to tag stable, or just do it now?

**Comment by robbieaverill** [comment]
Go for gold :-)

**Comment by NightJar** [comment]
Thanks for confirming.
FTR: waiting for consensus from folks outside of this thread. Sounds like there's some reservation around (more 'real world') testing.
