### ISSUE TITLE
CookieStore doesn't always return something

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-hybridsessions#85]
May get the error when logging out of the CMS.  Prevents logging in again

`error-log.ERROR: Uncaught Exception TypeError: "SilverStripe\HybridSessions\Store\CookieStore::read(): Return value must be of type string|false, none returned" at /sites/somesite/releases/somerelease/vendor/silverstripe/hybridsessions/src/Store/CookieStore.php line 113 {"exception":"[object] (TypeError(code: 0): SilverStripe\\HybridSessions\\Store\\CookieStore::read(): Return value must be of type string|false, none returned at /sites/somesite/releases/somerelease/vendor/silverstripe/hybridsessions/src/Store/CookieStore.php:113)"} []`

### PRs
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/84

**Comment by GuySartorelli** [comment]
PR merged
